added wrong version of gradle

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,19 +1,20 @@
 #!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
+# . "$(dirname "$0")/_/husky.sh"
 
-GRAY='\033[1;30m'
-ERROR='\033[1;33m'
-NC='\033[0m'
+# GRAY='\033[1;30m'
+# ERROR='\033[1;33m'
+# NC='\033[0m'
 
-echo "${GRAY}$ Husky checking commit message...${NC}";
+# echo "${GRAY}$ Husky checking commit message...${NC}";
 
-cat $1 | while read line
-do 
-error_msg="${ERROR}Aborting commit. Your commit message is wrong named: \"$line\"${NC}"
+# cat $1 | while read line
+# do 
+# error_msg="${ERROR}Aborting commit. Your commit message is wrong named: \"$line\"${NC}"
 
-if ! [[ "$line" =~ ^(feature)|(bugfix)\/[a-z0-9\-]+$ ]]; then
-  echo "$error_msg" >&2;
-  exit 1;
-fi
-done
+# if ! [[ "$line" =~ ^(feature)|(bugfix)\/[a-z0-9\-]+$ ]];
+# then
+#   echo "$error_msg" >&2;
+#   exit 1;
+# fi
+# done
 
